### ISSUE TITLE
Strange error

### ISSUE THREAD

**Issue by artrag** [santiontanon/mdlz80optimizer#53]
I'm trying to run MDL on an ASM  file generated by SDCC
This is the error I get

C:\MSXgl-1.0.0\projects>java -jar mdl.jar AfterBurner\out\template.asm -dialect sdcc -so speed
Exception in thread "main" java.lang.NoSuchMethodError: java.lang.String.isBlank()Z
        at code.CodeStatement.toStringUsingRootPath(CodeStatement.java:523)
        at code.CodeStatement.toString(CodeStatement.java:286)
        at java.lang.String.valueOf(Unknown Source)
        at java.lang.StringBuilder.append(Unknown Source)
        at workers.searchopt.SearchBasedOptimizer.optimizeStartingFromLine(SearchBasedOptimizer.java:887)
        at workers.searchopt.SearchBasedOptimizer.workOptimize(SearchBasedOptimizer.java:574)
        at workers.searchopt.SearchBasedOptimizer.work(SearchBasedOptimizer.java:294)
        at cl.MDLConfig.executeWorkers(MDLConfig.java:270)
        at cl.Main.main(Main.java:85)

The file template.asm is herein attached

[template.zip](https://github.com/user-attachments/files/16494984/template.zip)

**Comment by artrag** [comment]
The problem was related to the Java version used.
Your MDL needs Java 11, I was using Java 8

**Comment by santiontanon** [comment]
oh, thanks for reporting! Since I state in the homepage that Java 8 is required! Let me remove the usage of the isBlank method!

**Comment by santiontanon** [comment]
alright, this commit hopefully fixes it: https://github.com/santiontanon/mdlz80optimizer/commit/75c6080b90b6f04282fd3f10da70c9291aba6c1d
